allowBuilds:
  '@parcel/watcher': true
  '@sentry/cli': true
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@next/env@16.3.1'
  - '@next/eslint-plugin-next@16.3.1'
  - '@next/swc-darwin-arm64@16.3.1'
  - '@next/swc-darwin-x64@16.3.1'
  - '@next/swc-linux-arm64-gnu@16.3.1'
  - '@next/swc-linux-arm64-musl@16.3.1'
  - '@next/swc-linux-x64-gnu@16.3.1'
  - '@next/swc-linux-x64-musl@16.3.1'
  - '@next/swc-win32-arm64-msvc@16.3.1'
  - '@next/swc-win32-x64-msvc@16.3.1'
  - '@storybook/addon-a11y@10.5.8'
  - '@storybook/addon-docs@10.5.8'
  - '@storybook/addon-onboarding@10.5.8'
  - '@storybook/addon-vitest@10.5.8'
  - '@storybook/builder-vite@10.5.8'
  - '@storybook/csf-plugin@10.5.8'
  - '@storybook/nextjs-vite@10.5.8'
  - '@storybook/react-dom-shim@10.5.8'
  - '@storybook/react-vite@10.5.8'
  - '@storybook/react@10.5.8'
  - eslint-config-next@16.3.1
  - eslint-plugin-storybook@10.5.8
  - next@16.3.1
  - storybook@10.5.8
  - '@sentry/browser-utils@10.74.0'
  - '@sentry/browser@10.74.0'
  - '@sentry/core@10.74.0'
  - '@sentry/feedback@10.74.0'
  - '@sentry/nextjs@10.74.0'
  - '@sentry/node-core@10.74.0'
  - '@sentry/node@10.74.0'
  - '@sentry/opentelemetry@10.74.0'
  - '@sentry/react@10.74.0'
  - '@sentry/replay-canvas@10.74.0'
  - '@sentry/replay@10.74.0'
  - '@sentry/server-utils@10.74.0'
  - '@sentry/vercel-edge@10.74.0'
  - '@types/react-dom@19.3.0'
  - '@types/react@19.3.0'
  - react-dom@19.3.0
  - react@19.3.0
  - scheduler@0.28.0
  - icu-minify@4.14.3 || 4.14.6
  - next-intl-swc-plugin-extractor@4.14.3 || 4.14.6
  - next-intl@4.14.3 || 4.14.6
  - use-intl@4.14.3 || 4.14.6
  - vite@8.3.0
  - antd@6.6.5
  - drizzle-kit@0.31.11
  - drizzle-orm@0.45.3
