// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as Icons from "@ant-design/icons";
import * as JsxRuntime from "react/jsx-runtime";

let LoadingOutlined = {};

function Loading$default(props) {
  let styles = (require("./loading.module.sass"));
  let iconStyle = {fontSize: 64};
  let textStyle = {fontSize: 24};
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("div", {
        children: JsxRuntime.jsx(Icons.LoadingOutlined, {
          style: Primitive_option.some(iconStyle)
        })
      }),
      JsxRuntime.jsx("div", {
        children: "Loading...",
        style: textStyle
      })
    ],
    className: styles.container
  });
}

let $$default = Loading$default;

export {
  LoadingOutlined,
  $$default as default,
}
/* @ant-design/icons Not a pure module */
