// Generated by ReScript, PLEASE EDIT WITH CARE


let Space = {};

let Divider = {};

let Tag = {};

let Button = {};

let Image = {};

let Text = {};

let Link = {};

let Typography = {
  Text: Text,
  Link: Link
};

let Tooltip = {};

let Popover = {};

let QRCode = {};

let Row = {};

let Col = {};

let Dropdown = {};

let ConfigProvider = {};

let AntdRegistry = {};

export {
  Space,
  Divider,
  Tag,
  Button,
  Image,
  Typography,
  Tooltip,
  Popover,
  QRCode,
  Row,
  Col,
  Dropdown,
  ConfigProvider,
  AntdRegistry,
}
/* No side effect */
