// Generated by ReScript, PLEASE EDIT WITH CARE


let MailOutlined = {};

let EnvironmentOutlined = {};

let ClockCircleOutlined = {};

let CameraOutlined = {};

let GithubOutlined = {};

let LinkedinOutlined = {};

let WechatOutlined = {};

let MenuOutlined = {};

let HomeOutlined = {};

let FileTextOutlined = {};

let LinkOutlined = {};

let MessageOutlined = {};

let FolderOpenOutlined = {};

export {
  MailOutlined,
  EnvironmentOutlined,
  ClockCircleOutlined,
  CameraOutlined,
  GithubOutlined,
  LinkedinOutlined,
  WechatOutlined,
  MenuOutlined,
  HomeOutlined,
  FileTextOutlined,
  LinkOutlined,
  MessageOutlined,
  FolderOpenOutlined,
}
/* No side effect */
