// Generated by ReScript, PLEASE EDIT WITH CARE


let MenuOutlined = {};

let MailOutlined = {};

let EnvironmentOutlined = {};

let ClockCircleOutlined = {};

let CameraOutlined = {};

let GithubOutlined = {};

let LinkedinOutlined = {};

let TwitterOutlined = {};

let WechatOutlined = {};

let QqOutlined = {};

let PhoneOutlined = {};

let HomeOutlined = {};

let UserOutlined = {};

let BookOutlined = {};

let FileOutlined = {};

let DownloadOutlined = {};

let LinkOutlined = {};

let GlobalOutlined = {};

export {
  MenuOutlined,
  MailOutlined,
  EnvironmentOutlined,
  ClockCircleOutlined,
  CameraOutlined,
  GithubOutlined,
  LinkedinOutlined,
  TwitterOutlined,
  WechatOutlined,
  QqOutlined,
  PhoneOutlined,
  HomeOutlined,
  UserOutlined,
  BookOutlined,
  FileOutlined,
  DownloadOutlined,
  LinkOutlined,
  GlobalOutlined,
}
/* No side effect */
