// Generated by ReScript, PLEASE EDIT WITH CARE


let Link = {};

let Image = {};

let Script = {};

let Google = {};

let Font = {
  Google: Google
};

export {
  Link,
  Image,
  Script,
  Font,
}
/* No side effect */
