// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Dayjs from "dayjs";
import Dayjs$1 from "dayjs";
import * as React from "react";
import Utc from "dayjs/plugin/utc";
import Timezone from "dayjs/plugin/timezone";

"use client"
;

function Now(props) {
  let match = React.useState(() => Dayjs$1());
  let setNow = match[1];
  React.useEffect(() => {
    Dayjs.default.extend(Utc);
    Dayjs.default.extend(Timezone);
    let intervalId = setInterval(() => setNow(param => Dayjs$1()), 1000);
    return () => {
      clearInterval(intervalId);
    };
  }, []);
  let spanElement = (function(content) {
    return <span suppressHydrationWarning>{content}</span>
  });
  return spanElement(match[0].tz("Asia/Taipei").format("dddd YYYY-MM-DD HH:mm:ss"));
}

let make = Now;

export {
  make,
}
/*  Not a pure module */
