// Generated by ReScript, PLEASE EDIT WITH CARE

import Dayjs from "dayjs";
import * as React from "react";
import * as JsxRuntime from "react/jsx-runtime";

import dayjs from "dayjs"
import utc from "dayjs/plugin/utc"
import timezone from "dayjs/plugin/timezone"
dayjs.extend(utc)
dayjs.extend(timezone)
;

function Now(props) {
  let match = React.useState(() => Dayjs());
  let setNow = match[1];
  React.useEffect(() => {
    let intervalId = setInterval(() => setNow(param => Dayjs()), 1000);
    return () => {
      clearInterval(intervalId);
    };
  }, []);
  return JsxRuntime.jsx("span", {
    children: match[0].tz("Asia/Taipei").format("dddd YYYY-MM-DD HH:mm:ss")
  });
}

let make = Now;

export {
  make,
}
/*  Not a pure module */
