// Generated by ReScript, PLEASE EDIT WITH CARE


let Space = {};

let Divider = {};

let Button = {};

let Dropdown = {};

let ConfigProvider = {};

let Tag = {};

let Image = {};

let Item = {};

let Timeline = {
  Item: Item
};

let Text = {};

let Title = {};

let Paragraph = {};

let Typography = {
  Text: Text,
  Title: Title,
  Paragraph: Paragraph
};

let Card = {};

let Item$1 = {};

let List = {
  Item: Item$1
};

export {
  Space,
  Divider,
  Button,
  Dropdown,
  ConfigProvider,
  Tag,
  Image,
  Timeline,
  Typography,
  Card,
  List,
}
/* No side effect */
