// Generated by ReScript, PLEASE EDIT WITH CARE


let Link = {};

let Image = {};

let Script = {};

let Router = {};

let SearchParams = {};

let Metadata = {};

let NotoSansSC = {};

let Font = {
  NotoSansSC: NotoSansSC
};

export {
  Link,
  Image,
  Script,
  Router,
  SearchParams,
  Metadata,
  Font,
}
/* No side effect */
