// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function OutsideLink(props) {
  let children = props.children;
  let href = props.href;
  let target = Core__Option.getOr(props.target, "_blank");
  let rel = Core__Option.getOr(props.rel, "noopener noreferrer");
  let content = children !== undefined ? children : (
      href !== undefined ? href : null
    );
  return JsxRuntime.jsx("a", {
    children: content,
    className: props.className,
    href: href,
    rel: rel,
    target: target
  });
}

let make = OutsideLink;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
