// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.js";
import * as JsxRuntime from "react/jsx-runtime";

function OutsideLink(props) {
  let href = props.href;
  let target = Core__Option.getOr(props.target, "_blank");
  let rel = Core__Option.getOr(props.rel, "noopener noreferrer");
  return JsxRuntime.jsx("a", {
    children: Core__Option.getOr(props.children, href !== undefined ? href : null),
    className: props.className,
    style: props.style,
    href: href,
    rel: rel,
    target: target,
    onClick: props.onClick
  });
}

let make = OutsideLink;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
