// Generated by ReScript, PLEASE EDIT WITH CARE


let url_resume_pdf_github = "https://github.com/cw1997/resume/releases/download/latest/changwei-resume.pdf";

let url_resume_pdf_release = "https://github.com/cw1997/resume/releases";

let url_resume_pdf_mirror = "/api/changwei-resume.pdf";

let url_resume_pdf_source = "https://github.com/cw1997/resume";

export {
  url_resume_pdf_github,
  url_resume_pdf_release,
  url_resume_pdf_mirror,
  url_resume_pdf_source,
}
/* No side effect */
