// Generated by ReScript, PLEASE EDIT WITH CARE


let urlResumePdfGithub = "https://github.com/cw1997/resume/releases/download/latest/changwei-resume.pdf";

let urlResumePdfRelease = "https://github.com/cw1997/resume/releases";

let urlResumePdfMirror = "/api/changwei-resume.pdf";

let urlResumePdfSource = "https://github.com/cw1997/resume";

export {
  urlResumePdfGithub,
  urlResumePdfRelease,
  urlResumePdfMirror,
  urlResumePdfSource,
}
/* No side effect */
